const stimuli = [
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 2)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 3)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 3)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 4)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 4)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 4)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 4)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 5)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 5)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 5)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 5)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 5)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 5)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 6)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 6)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 6)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 6)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 6)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 6)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 7)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 7)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 7)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 7)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 7)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 8)},
    {sequence: jsPsych.randomization.sampleWithoutReplacement([...Array(16).keys()], 8)},
];